// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5CfuAKs27-BfVLt3xZniy5iaGZCZvaCg',
    appId: '1:1030419831779:web:edc7f000a2968f77f99ed6',
    messagingSenderId: '1030419831779',
    projectId: 'emart-474bd',
    authDomain: 'emart-474bd.firebaseapp.com',
    storageBucket: 'emart-474bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwnU-gxJBE1ApBZM2Km56NYvJmOYLkbXk',
    appId: '1:1030419831779:android:dd371d4701dbb2b7f99ed6',
    messagingSenderId: '1030419831779',
    projectId: 'emart-474bd',
    storageBucket: 'emart-474bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXrWP0aUo2qpcMaBwN9dOYihB5WlOnSw',
    appId: '1:1030419831779:ios:c7badce836a94af4f99ed6',
    messagingSenderId: '1030419831779',
    projectId: 'emart-474bd',
    storageBucket: 'emart-474bd.appspot.com',
    iosClientId: '1030419831779-vk5iokndheebelv6726e5tu3j8jt6f16.apps.googleusercontent.com',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrXrWP0aUo2qpcMaBwN9dOYihB5WlOnSw',
    appId: '1:1030419831779:ios:c7badce836a94af4f99ed6',
    messagingSenderId: '1030419831779',
    projectId: 'emart-474bd',
    storageBucket: 'emart-474bd.appspot.com',
    iosClientId: '1030419831779-vk5iokndheebelv6726e5tu3j8jt6f16.apps.googleusercontent.com',
    iosBundleId: 'com.example.emart',
  );
}
